### PR TITLE
Deps, install properly, further disallow multiple versions

### PR DESCRIPTION
**Pull request by commiebstrd**
Essentially an entire rewrite:

* searched directories for missing links, linking compat or adding deps as needed
* enforce same destination of `/opt/binaryninja` we already conflict via package names, keep structure, plugins, and tutorials as simple as possible
* remove preload junk in favor of much less hacky but still not great local links
* fix version and hash finding
* move desktop internal to PKGBUILD for dynamic generation as the only indicator of install type aside from package name
* update .srcinfo
* merge your 2 unsynced repos + AUR into a single correct set. (please delete the dev thing and keep this in sync with aur if you're going to maintain packages in this state)

This PKGBUILD has been tested on my personal and commercial zips, hashes aren't available for commercial but the rest applies fine! Thanks for starting a pkgbuild, just needed a good bit of work as you indicated in comments.

### CODE REVIEW

**Comment by Manouchehri** [comment]
Thanks!

If possible, would you mind rebasing onto the current master? (The AUR doesn't allow me to lazily `git push --force`.)

**Comment by commiebstrd** [comment]
I wondered how that might work out, can do later today or tomorrow.

**Comment by Manouchehri** [comment]
@commiebstrd Does everything look okay now?

**Comment by commiebstrd** [comment]
Probably should have commented earlier, was holding off on the merge. Found we can remove most qt libs in favor of system without issue. also made it more friendly for one pkgbuild for multiple editions. I'll submit another pr tonight so we can discuss.

**Pull request merged**
